Add: 모델 추가
wecode-bootcamp-korea/23-2nd-Homestagram-backend pull request #1
Opened 2021-08-18 08:05 UTC by bigfanoftim

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 모델 추가
		 
## 수정 사항들 자세한 내용
- 모델 추가

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-08-18 09:33 UTC, kst6294 requested changes
확인바랍니다!

2021-08-18 11:08 UTC, bigfanoftim commented on postings/models.py
> +    image_url   = models.ImageField(upload_to='images')
이미지 업로드 기능도 urlfield로 사용 가능한가요??

2021-08-19 01:01 UTC, kst6294 requested changes
확인바랍니다!

2021-08-19 01:01 UTC, kst6294 commented on postings/models.py
> +    image_url   = models.ImageField(upload_to='images')
이미지도 s3 를 사용하시는건 어떤가요?

2021-08-19 01:14 UTC, bigfanoftim commented
s3에 저장하는 방식으로 변경 후 다시 PR 올리겠습니다!

2021-08-19 05:03 UTC, kst6294 commented
LGTM 👍

2021-08-19 05:03 UTC, merged