[23기 송진수] Add: 유저 팔로우 기능
wecode-bootcamp-korea/23-2nd-Homestagram-backend pull request #12
Opened 2021-08-24 07:36 UTC by jssong1592

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 게시글 작성자 팔로우/언팔로우 기능
		 
## 수정 사항들 자세한 내용
- 로그인 상태에서 팔로우 버튼을 눌러 게시글의 작성자 정보가 담긴 요청을 받으면, 팔로우 데이터를 생성합니다.
- 동일한 요청을 받았으나 팔로우 데이터가 이미 존재할 시, 해당 데이터를 삭제하여 언팔로우 합니다.

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

## 유닛 테스트 결과 화면
![image](https://user-images.githubusercontent.com/84955774/130576069-74cdfc31-0a8f-4319-bc5c-b6aaf5ff4760.png)

## Postman 결과 화면
![image](https://user-images.githubusercontent.com/84955774/130576243-1aa391a1-bb7a-44fe-8d55-ac62af55738d.png)

2021-08-24 08:17 UTC, jssong1592 commented
컨플릭트 해결하고 다시 push했습니다!

2021-08-25 01:40 UTC, kst6294 requested changes

2021-08-25 01:40 UTC, kst6294 commented on users/views.py
> +            followed = User.objects.get(nickname=json.loads(request.body)['nickname'])
데이터상에 유니크한 값이기 때문에 nickname으로 조회하신 것 같은데, 닉네임보다는 그 사용자의 고유번호로 조회를 하는게 어떤가요?

2021-08-25 01:58 UTC, jssong1592 commented on users/views.py
> +            followed = User.objects.get(nickname=json.loads(request.body)['nickname'])
수정했습니다.

![image](https://user-images.githubusercontent.com/84955774/130713680-ff83be56-b549-4178-ba6a-12b2953cea30.png)

2021-08-25 02:43 UTC, kst6294 approved these changes

2021-08-25 02:43 UTC, merged