[23기 장호준] Modify : 게시글 등록
wecode-bootcamp-korea/23-2nd-Homestagram-backend pull request #13
Opened 2021-08-24 07:48 UTC by bigfanoftim

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 게시글 등록
		 
## 수정 사항들 자세한 내용
- 게시글 등록 시에 태그 정보도 함께 등록되는 기능
- 유닛 테스트 완료

## 기타 질문 및 특이 사항 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-08-24 08:03 UTC, kst6294 reviewed
피드백 남긴 부분 기능 설명한번 부탁드려요!

2021-08-24 08:03 UTC, kst6294 commented on postings/views.py
> +                    image_url   = 'https://homestagram.s3.ap-northeast-2.amazonaws.com/' + upload_key,
주소는 따로 관리해주시는게 어떤가요~!

2021-08-24 08:03 UTC, kst6294 commented on postings/views.py
> +                max_id         = Posting.objects.filter(user_id=user.id).aggregate(id=Max('id'))['id']
max_id 를 어떻게 활용하는지 설명해주세요!

2021-08-24 08:08 UTC, bigfanoftim commented on postings/views.py
> +                max_id         = Posting.objects.filter(user_id=user.id).aggregate(id=Max('id'))['id']
view가 호출될 때 프론트로 부터 아직 생성되지 않은 posting_id를 받아올 수 없기 때문에 순간 posting이 생성되자마자 가장 최근에 생성된 posting에 tag를 등록하는 방법을 선택했습니다!

2021-08-24 08:08 UTC, bigfanoftim commented on postings/views.py
> +                    image_url   = 'https://homestagram.s3.ap-northeast-2.amazonaws.com/' + upload_key,
넵!

2021-08-25 01:51 UTC, kst6294 requested changes

2021-08-25 01:51 UTC, kst6294 commented on postings/views.py
> +                max_id         = Posting.objects.filter(user_id=user.id).aggregate(id=Max('id'))['id']
create 할 때 반환되는 인스턴스를 활용할 수 없나요?

2021-08-25 05:58 UTC, kst6294 approved these changes

2021-08-25 05:58 UTC, merged