[23기 송진수] Add: 소셜 로그인 API
wecode-bootcamp-korea/23-2nd-Homestagram-backend pull request #3
Opened 2021-08-19 12:38 UTC by jssong1592

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 카카오 소셜 로그인 API 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 클라이언트로부터 카카오 액세스 토큰을 받아 카카오 api로부터 유저 정보 호출
- 응답 받은유저 정보와 DB를 대조하여 유저 가입 여부 확인
- 가입 내역이 확인되면 토큰을 생성하고, 클라이언트에서 필요로 하는 DB상 유저 정보와 함께 응답 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-08-20 01:01 UTC, kst6294 requested changes
피드백 확인바랍니다!

2021-08-20 01:01 UTC, kst6294 commented on users/views.py
> +                return JsonResponse({'MESSAGE':'NEED_SIGN_UP'}, status=401)
회원가입 절차를 수행하지 않고 카카오 로그인 정보로 회원정보를 생성 혹은 불러들이기 때문에, get_or_create 메소드를 활용해보시는건 어떤가요?

2021-08-20 01:45 UTC, jssong1592 commented on users/views.py
> +                return JsonResponse({'MESSAGE':'NEED_SIGN_UP'}, status=401)
순태님 안녕하세요! 
NEED_SIGN_UP 메시지를 프론트가 받을 경우 회원가입 페이지로 리다이렉트시키고, 가입 페이지 내에서 사이트에서 사용할 자체 닉네임을 추가로 입력 후 가입시키는 절차로 프론트와 의견을 나눈 바 있습니다.
이 경우에도 같은 뷰에서 get_or_create 메소드를 활용할 수 있는 방법이 있을까요?

2021-08-20 10:32 UTC, jssong1592 commented on users/views.py
> +                return JsonResponse({'MESSAGE':'NEED_SIGN_UP'}, status=401)
조언 주신 대로 get_or_create 메소드로 로그인/회원가입 기능을 통합하여 코드 중복을 줄였습니다.
닉네임 추가 입력 API는 완전히 분리된 기능을 하도록 구현하겠습니다!

2021-08-20 10:33 UTC, jssong1592 commented
조언 주신 대로 get_or_create 메소드로 로그인/회원가입 기능을 통합하여 코드 중복을 줄였습니다.
닉네임 추가 입력 API는 완전히 분리된 기능을 하도록 구현하겠습니다!

2021-08-21 01:51 UTC, kst6294 reviewed
통신결과 및 유닛테스트 동작확인 결과도 같이 올려주세요

2021-08-21 01:51 UTC, kst6294 commented on users/views.py
> +                return JsonResponse({'token' : access_token, 'MESSAGE':'NEED_NICKNAME'}, status=200)
is_created 경우에는 당연히 nickname 이 없는 경우가 되기 때문에 현재와 같은 조건은 불필요해보입니다.

2021-08-21 01:51 UTC, kst6294 commented on users/views.py
> +                return JsonResponse({'MESSAGE':'NEED_EMAIL_AGREEMENT'}, status=400)
프론트에서 사용자가 로그인을 할 때 이메일정보 제공에 동의를 해야만 토큰이 생성되고, 그 토큰으로 백엔드에서 카카오api 로 정보를 요청할 수 있는 것으로 알 고 있습니다. 확인 부탁드려요!

2021-08-21 01:51 UTC, kst6294 commented on users/views.py
> +            access_token = jwt.encode({'id': user.id}, SECRET_KEY, algorithm='HS256')
algorithm 은 my_settings.py 에 추가해서 사용해주세요!

2021-08-22 01:08 UTC, jssong1592 commented on users/views.py
> +                return JsonResponse({'MESSAGE':'NEED_EMAIL_AGREEMENT'}, status=400)
프론트단에서 처리할 수 있는 토큰 문제를 너무 깊게 생각한 것 같습니다. 삭제하도록 하겠습니다!

2021-08-22 01:17 UTC, jssong1592 commented
![image](https://user-images.githubusercontent.com/84955774/130338805-e4f5f35b-7ca8-4d66-aea2-9c89b353e92b.png)
![image](https://user-images.githubusercontent.com/84955774/130338821-22248ab3-cc60-4b78-a0da-1cc027139db9.png)

통신결과와 유닛테스트 결과 캡쳐하여 올립니다!

2021-08-22 13:42 UTC, jssong1592 commented
Conflict 해결 후 다시 request 올립니다.

2021-08-23 01:18 UTC, kst6294 requested changes

2021-08-23 01:18 UTC, kst6294 commented on users/views.py
> +                return JsonResponse({'token' : access_token, 'MESSAGE':'NEED_NICKNAME'}, status=200)
사용자의 nickname 이 없는 경우의 조건을 작성한 이유가 있을까요?
nickname 이 존재하지 않는 다는 것을 반환하기 위함인것 같네요. 하지만 아래에서 return 을 할 때 user.nickname 에서 반환할 사용자의 nickname 이 없는 경우 None 반환해도 괜찮지 않을까요?

2021-08-23 01:44 UTC, jssong1592 commented on users/views.py
> +                return JsonResponse({'token' : access_token, 'MESSAGE':'NEED_NICKNAME'}, status=200)
순태님 말씀대로 굳이 에러 핸들링 없이 nickname을 None으로 반환해도 프론트에서 이를 캐치해서 닉네임 설정 페이지로 리다이렉트시켜도 무방할거라는 말씀이시죠?!

2021-08-23 04:43 UTC, jssong1592 commented on users/views.py
> +                return JsonResponse({'token' : access_token, 'MESSAGE':'NEED_NICKNAME'}, status=200)
해당 부분 삭제하였습니다!

2021-08-23 04:44 UTC, jssong1592 commented
user.nickname = None을 반환하는 경우의 유닛테스트 결과 화면입니다!

![image](https://user-images.githubusercontent.com/84955774/130391109-38342426-f0f4-40fc-acda-8daaffc7b943.png)

2021-08-23 05:48 UTC, kst6294 approved these changes

2021-08-23 05:48 UTC, merged