[23기 송진수] Add: 로그인 Decorator
wecode-bootcamp-korea/23-2nd-Homestagram-backend pull request #6
Opened 2021-08-20 12:43 UTC by jssong1592

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 로그인 decorator 구현
		 
## 수정 사항들 자세한 내용
- users/utils.py에 로그인 decorator를 클래스 형태로 구현하였습니다.
- 아래 케이스들에 대하여 각각 에러 핸들링을 하였습니다.
1. 닉네임이 설정되지 않은 경우(닉네임을 설정하여 최종가입 완료 필요) 
2. 토큰이 없는 경우(로그인X)
3. 잘못된 토큰인 경우 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-08-21 01:52 UTC, kst6294 requested changes
간단한 수정사항만 반영해주세요 👍

2021-08-21 01:52 UTC, kst6294 commented on users/utils.py
> +                payload       = jwt.decode(token, SECRET_KEY, algorithms='HS256')
algorithm 은 my_settings.py 에 추가해서 사용해주세요!

2021-08-22 00:43 UTC, jssong1592 commented on users/utils.py
> +                payload       = jwt.decode(token, SECRET_KEY, algorithms='HS256')
수정했습니다!

2021-08-22 00:44 UTC, jssong1592 commented
![image](https://user-images.githubusercontent.com/84955774/130338314-b73b558a-5fc2-4daa-84df-58068a7a8de0.png)

유닛 테스트 실행 결과 캡쳐하여 올립니다!

2021-08-22 06:26 UTC, merged